# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freq_scrap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='freq_scrap.proto',
  package='freqscrap',
  syntax='proto3',
  serialized_options=b'\n\021io.grpc.freqscrapB\016FreqScrapProtoP\001\242\002\002FS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66req_scrap.proto\x12\tfreqscrap\"]\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x15\n\rscrap_domains\x18\x02 \x01(\t\x12\x0e\n\x06ngrams\x18\x03 \x01(\x05\x12\x0b\n\x03top\x18\x04 \x01(\x05\x12\x11\n\tmax_level\x18\x05 \x01(\x05\".\n\x08Response\x12\"\n\x07results\x18\x01 \x03(\x0b\x32\x11.freqscrap.Result\"$\n\x06Result\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0c\n\x04\x66req\x18\x02 \x01(\x05\x32\x41\n\tFreqScrap\x12\x34\n\x07GetFreq\x12\x12.freqscrap.Request\x1a\x13.freqscrap.Response\"\x00\x42*\n\x11io.grpc.freqscrapB\x0e\x46reqScrapProtoP\x01\xa2\x02\x02\x46Sb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='freqscrap.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='freqscrap.Request.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scrap_domains', full_name='freqscrap.Request.scrap_domains', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ngrams', full_name='freqscrap.Request.ngrams', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='freqscrap.Request.top', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_level', full_name='freqscrap.Request.max_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=124,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='freqscrap.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='freqscrap.Response.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=172,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='freqscrap.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='freqscrap.Result.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freq', full_name='freqscrap.Result.freq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=210,
)

_RESPONSE.fields_by_name['results'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'freq_scrap_pb2'
  # @@protoc_insertion_point(class_scope:freqscrap.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'freq_scrap_pb2'
  # @@protoc_insertion_point(class_scope:freqscrap.Response)
  })
_sym_db.RegisterMessage(Response)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'freq_scrap_pb2'
  # @@protoc_insertion_point(class_scope:freqscrap.Result)
  })
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None

_FREQSCRAP = _descriptor.ServiceDescriptor(
  name='FreqScrap',
  full_name='freqscrap.FreqScrap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=212,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFreq',
    full_name='freqscrap.FreqScrap.GetFreq',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FREQSCRAP)

DESCRIPTOR.services_by_name['FreqScrap'] = _FREQSCRAP

# @@protoc_insertion_point(module_scope)
